export const serviceCatalog = [
  {
    slug: 'japan-market-localization',
    number: '01',
    title: 'Japan Market Entry & Localization',
    headline: 'Adapt Global Creative for Japan',
    description:
      'We help international brands adapt positioning, messaging, and execution for Japan so launches feel considered, credible, and locally relevant.',
    intro:
      'We do not just translate — we adapt. Streetshow helps premium brands reshape messaging, visuals, and execution for Japanese audiences while protecting core brand equity.',
    whyTitle: 'Why This Matters in Japan',
    whyBody:
      'Market entry in Japan fails when translation is mistaken for adaptation. Premium brands need positioning, messaging, and execution aligned with Japanese expectations from the start.',
    mistakesTitle: 'Where Brands Usually Get It Wrong',
    mistakes: [
      'Treating Japan like a standard regional rollout',
      'Using translation without cultural adaptation',
      'Separating strategy, localization, and production across disconnected vendors',
    ],
    features: [
      'Cultural consulting and market research',
      'Creative adaptation and transcreation',
      'Visual and messaging localization',
      'Talent and influencer coordination',
      'Media strategy for Japan',
      'Ongoing campaign optimization',
    ],
    idealFor: ['Foreign brands entering Japan', 'Global campaign rollouts', 'Product launches', 'Rebranding for Japan'],
    relatedProjects: ['japan-market-localization-campaign'],
    relatedServices: ['video-production-japan', 'photography-cgi-japan', 'hospitality-creative-strategy-japan'],
  },
  {
    slug: 'hospitality-creative-strategy-japan',
    number: '02',
    title: 'Hospitality Creative Strategy & Production',
    headline: 'Creative Strategy & Content for Hotels and Hospitality Brands in Japan',
    description:
      'We support luxury hotels, resorts, and destination properties with strategy-led creative designed to strengthen visibility, booking intent, and premium brand perception.',
    intro:
      'We help hotels, resorts, and hospitality brands in Japan increase bookings and long-term revenue through strategy-first creative.',
    whyTitle: 'Why This Matters in Japan',
    whyBody:
      'In luxury hospitality, visual and messaging quality directly influence trust, desirability, and booking intent. In Japan, premium perception is shaped by restraint, consistency, and local relevance.',
    mistakesTitle: 'Where Brands Usually Get It Wrong',
    mistakes: [
      'Treating hospitality content as decoration rather than revenue support',
      'Using generic luxury cues that do not resonate locally',
      'Failing to align campaign assets with guest expectations and booking behavior',
    ],
    features: [
      'Hospitality-focused creative strategy',
      'Video and photography for hotels and resorts',
      'Campaign planning for peak and off-peak seasons',
      'Content systems designed to increase bookings and ROI',
      'Creative optimization for ads, social, and digital platforms',
    ],
    idealFor: ['Luxury and boutique hotels', 'Resorts and destination properties', 'Hospitality brands entering or repositioning in Japan', 'Hotels improving online conversion'],
    relatedProjects: ['japan-luxury-resort-video-campaign'],
    relatedServices: ['video-production-japan', 'photography-cgi-japan', 'japan-market-localization'],
  },
  {
    slug: 'video-production-japan',
    number: '03',
    title: 'Video Production in Japan',
    headline: 'Commercials & Brand Films Made in Japan',
    description:
      'High-level production for premium campaigns, launches, and brand storytelling managed locally in Japan with the quality control international teams expect.',
    intro:
      'Full-service video production for brands targeting the Japanese market, from concept through delivery across commercials, brand films, social content, and campaign videos.',
    whyTitle: 'Why This Matters in Japan',
    whyBody:
      'Premium campaigns in Japan require local control without compromising global brand standards. Production quality, local coordination, and cultural fit all influence the final result.',
    mistakesTitle: 'Where Brands Usually Get It Wrong',
    mistakes: [
      'Optimizing for speed instead of brand sensitivity',
      'Running production without enough local context',
      'Treating Japan as execution-only instead of a strategic market',
    ],
    features: [
      'Creative concept and scripting',
      'Location scouting across Japan',
      'Talent casting and coordination',
      'Full production crew',
      'Post-production and color grading',
      'Multi-format delivery',
    ],
    idealFor: ['TV commercials', 'Digital advertising', 'Brand documentaries', 'Product videos'],
    relatedProjects: ['tokyo-luxury-brand-video-campaign', 'japan-market-localization-campaign'],
    relatedServices: ['japan-market-localization', '3d-cgi-production', 'hospitality-creative-strategy-japan'],
  },
  {
    slug: 'photography-cgi-japan',
    number: '04',
    title: 'Photography & CGI',
    headline: 'High-End Photography & CGI Across Japan',
    description:
      'Premium visual production for hospitality, lifestyle, real estate, and consumer brands that need launch-ready visual systems and long-term brand consistency.',
    intro:
      'From product photography to editorial shoots and CGI visuals, we deliver premium visual content for advertising, hospitality, lifestyle, and brand campaigns.',
    whyTitle: 'Why This Matters in Japan',
    whyBody:
      'Premium visual systems shape how a brand is priced and perceived. In Japan, image quality and refinement often influence trust before any message is read.',
    mistakesTitle: 'Where Brands Usually Get It Wrong',
    mistakes: [
      'Using inconsistent visuals across channels',
      'Producing images that feel generic instead of premium',
      'Underestimating how visual quality affects credibility',
    ],
    features: [
      'Product and still life photography',
      'Lifestyle and editorial shoots',
      'CGI product visualization',
      'Location scouting and coordination',
      'Studio rental and set design',
      'Post-production and retouching',
    ],
    idealFor: ['Advertising campaigns', 'E-commerce imagery', 'Hotel and hospitality', 'Fashion and lifestyle'],
    relatedProjects: ['tokyo-editorial-photography'],
    relatedServices: ['video-production-japan', 'japan-market-localization', 'hospitality-creative-strategy-japan'],
  },
  {
    slug: '3d-anamorphic-billboards-japan',
    number: '05',
    title: '3D Anamorphic Billboards',
    headline: 'Naked-Eye 3D That Stops Traffic',
    description:
      'High-visibility 3D billboard production for launch moments, activations, and attention-led campaigns across Japan’s major urban locations.',
    intro:
      'We create immersive 3D billboard content for premium LED screens across Japan, built to maximize visibility and launch impact.',
    whyTitle: 'Why This Matters in Japan',
    whyBody:
      'High-visibility formats only create value when they align with launch timing, location context, and brand positioning. In Japan, spectacle without strategic fit can weaken premium perception.',
    mistakesTitle: 'Where Brands Usually Get It Wrong',
    mistakes: [
      'Using 3D billboards as a gimmick without launch strategy',
      'Designing for novelty instead of brand alignment',
      'Ignoring how OOH execution affects long-term perception',
    ],
    features: [
      'Concept development and creative direction',
      '3D modeling and animation',
      'Anamorphic perspective calculation',
      'Screen-specific optimization',
      'Media placement coordination',
      'Campaign performance tracking',
    ],
    idealFor: ['Product launches', 'Brand awareness campaigns', 'Market entry activations', 'Seasonal promotions'],
    relatedProjects: ['shibuya-3d-anamorphic-billboard'],
    relatedServices: ['3d-cgi-production', 'video-production-japan'],
  },
];

export const projectCatalog = [
  {
    slug: 'shibuya-3d-anamorphic-billboard',
    title: '3D Anamorphic Billboard in Shibuya',
    proofLine: '3D Anamorphic · Japan Market Entry · 2024',
    client: 'Global consumer technology brand',
    year: '2024',
    category: '3D Anamorphic',
    intro: 'A high-impact naked-eye 3D billboard campaign for a global brand launching in Tokyo, designed to maximize visibility and drive awareness during the product launch window.',
    description: 'A launch-focused Tokyo billboard execution built for visibility, social shareability, and premium first-impression impact.',
    media: {
      image: 'https://customer-assets.emergentagent.com/job_nippon-replace/artifacts/unjldvln_Tokyo-Japan%203D%20Anamorphic%20Billboard%20%20.jpg',
      alt: '3D anamorphic billboard campaign execution in Tokyo, Japan',
    },
    servicesProvided: ['3D Animation & Modeling', 'Anamorphic Perspective Design', 'Billboard Content Production', 'Screen-Specific Optimization'],
    deliverables: ['3D Animation', 'Billboard Content', 'Social Cutdowns', 'Campaign Assets'],
    projectFocus: ['Brand awareness at product launch', 'High-traffic location visibility', 'Social media shareability', 'Market entry impact'],
    caseStudy: {
      context: 'A global consumer technology brand needed a launch moment in Tokyo that could break through visual saturation and earn immediate attention in one of the world\'s most competitive outdoor media environments.',
      challenge: 'The work needed to feel premium, technically precise, and socially shareable while adapting to the constraints of a flagship 3D billboard format and a tightly timed launch window.',
      response: 'We developed anamorphic creative built specifically for the screen geometry, launch context, and audience behavior in Shibuya, combining 3D design, motion logic, and screen-specific optimization.',
      execution: 'Streetshow handled concept development, 3D production, perspective calibration, and final content delivery so the campaign could launch cleanly across the target billboard environment.',
      outcome: 'The result was a high-visibility launch asset designed to amplify awareness, increase social shareability, and give the product release a more premium public debut in Tokyo.',
    },
    relatedServices: ['3d-anamorphic-billboards-japan', '3d-cgi-production'],
  },
  {
    slug: 'tokyo-luxury-brand-video-campaign',
    title: 'Luxury Brand Video Campaign in Tokyo',
    proofLine: 'Luxury Brand Campaign · Japan Market Entry · 2024',
    client: 'European luxury fashion house',
    year: '2024',
    category: 'Video Production',
    intro: 'A comprehensive video campaign for a European luxury fashion house entering the Japanese market, balancing global brand consistency with local cultural fit.',
    description: 'A Japan-entry campaign for a European luxury brand, balancing global consistency with local cultural fit.',
    media: {
      image: 'https://customer-assets.emergentagent.com/job_nippon-replace/artifacts/0ox8zb63_treetshow-luxury-video-campaign-japan-placeholder.jpg',
      alt: 'Luxury brand video campaign production for Japan market entry',
    },
    servicesProvided: ['Creative Direction', 'Video Production', 'Location Scouting', 'Talent Coordination', 'Post-Production'],
    deliverables: ['TVC', 'Digital Films', 'Photography', 'Social Content'],
    projectFocus: ['Japan market entry', 'Cultural adaptation', 'Premium brand positioning', 'Multi-channel campaign'],
    caseStudy: {
      context: 'A European luxury fashion house was entering Japan and needed campaign content that could preserve global brand codes while feeling locally credible for a premium audience.',
      challenge: 'The campaign had to bridge international brand consistency, local cultural nuance, and multi-format delivery across TV, digital, and social without becoming generic or over-localized.',
      response: 'We shaped a Tokyo-based production approach that aligned creative direction, casting, locations, and content structure with the expectations of the Japanese luxury market.',
      execution: 'Streetshow managed production from concept through post, coordinating locations, talent, and edit outputs across campaign formats to keep the launch cohesive.',
      outcome: 'The finished campaign gave the brand a more market-ready presence in Japan, with premium visual assets built to support launch visibility, brand perception, and cross-channel consistency.',
    },
    relatedServices: ['video-production-japan', 'japan-market-localization'],
  },
  {
    slug: 'japan-market-localization-campaign',
    title: 'Japan Market Localization Campaign',
    proofLine: 'Localization · Premium Brand Campaign · 2025',
    client: 'International food brand entering Japan',
    year: '2025',
    category: 'Localization',
    intro: 'Creative localization of a global digital campaign for Japanese audiences, adapting messaging, visual language, and creative direction while preserving brand consistency.',
    description: 'Creative adaptation for Japanese audiences across digital channels, designed to preserve brand intent while improving local resonance.',
    media: {
      image: 'https://customer-assets.emergentagent.com/job_03b4617a-d997-493a-9fa8-086dcef97522/artifacts/6zcnpeye_streetshow-japan-market-localization-Picture.jpg',
      alt: 'Japan market localization strategy and creative adaptation process',
    },
    servicesProvided: ['Cultural Strategy', 'Creative Localization', 'Visual Adaptation', 'Digital Content Production', 'Campaign Management'],
    deliverables: ['Localized Campaign Assets', 'Digital Content', 'Social Media Content', 'Cultural Strategy Document'],
    projectFocus: ['Cultural adaptation', 'Japan market resonance', 'Brand consistency', 'Digital platform optimization'],
    caseStudy: {
      context: 'An international food brand needed to adapt a global campaign for Japanese audiences across digital channels without losing the original strategic intent of the parent campaign.',
      challenge: 'Direct translation would not have been enough. The campaign needed a more culturally tuned visual language, stronger local messaging fit, and execution that felt designed for Japan rather than imported into it.',
      response: 'We approached the work as creative adaptation rather than translation, reshaping messaging, visual emphasis, and asset logic around local audience expectations and platform behavior.',
      execution: 'Streetshow delivered cultural strategy, localized content direction, visual adaptation, and digital asset production to support rollout across the relevant channels.',
      outcome: 'The campaign was positioned to resonate more authentically in Japan while preserving brand consistency, improving the likelihood of stronger audience relevance and cleaner market entry communication.',
    },
    relatedServices: ['japan-market-localization', 'video-production-japan'],
  },
  {
    slug: 'tokyo-editorial-photography',
    title: 'Editorial Photography in Tokyo',
    proofLine: 'Editorial Photography · Premium Lifestyle · 2023',
    client: 'Luxury lifestyle editorial title',
    year: '2023',
    category: 'Photography',
    intro: 'A premium editorial photography series for a luxury lifestyle title, shot across multiple iconic Tokyo locations for both print and digital publication.',
    description: 'A premium editorial series built to support elevated visual storytelling across print and digital publication.',
    media: {
      image: 'https://images.unsplash.com/photo-1617463874381-85b513b3e991?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NTYxOTF8MHwxfHNlYXJjaHwxfHxwaG90b2dyYXBoeSUyMHN0dWRpb3xlbnwwfHx8fDE3NjkzNTMxNDJ8MA&ixlib=rb-4.1.0&q=85&w=1200',
      alt: 'Professional photography studio environment with lighting equipment',
    },
    servicesProvided: ['Editorial Photography', 'Location Coordination', 'Styling Direction', 'Post-Production', 'Asset Management'],
    deliverables: ['Editorial Shoot', 'Post-Production', 'Print Assets', 'Digital Assets'],
    projectFocus: ['Premium visual storytelling', 'Multi-location production', 'Print and digital optimization', 'Lifestyle brand alignment'],
    caseStudy: {
      context: 'A luxury lifestyle editorial title commissioned a Tokyo-based photography series that needed to feel elevated, contemporary, and aligned with premium fashion and culture audiences.',
      challenge: 'The production had to maintain editorial sophistication across multiple locations while keeping styling, pacing, and post-production coherent enough for both print and digital use.',
      response: 'We designed the shoot around location selection, styling direction, and visual rhythm that would support both editorial storytelling and premium brand alignment.',
      execution: 'Streetshow coordinated the photography production, location flow, styling support, and post-production finishing to ensure the full asset set remained cohesive across formats.',
      outcome: 'The final series delivered a stronger editorial package with premium visual consistency suitable for both print presentation and digital publication.',
    },
    relatedServices: ['photography-cgi-japan', 'hospitality-creative-strategy-japan'],
  },
  {
    slug: 'japan-electronics-cgi-visualization',
    title: 'CGI Product Visualization in Japan',
    proofLine: 'CGI Visualization · Consumer Electronics · 2024',
    client: 'Premium consumer electronics brand',
    year: '2024',
    category: 'CGI',
    intro: 'Photorealistic 3D product visualization for a global electronics brand\'s Japan market campaign, designed for premium product storytelling across multiple formats.',
    description: 'Photoreal product visualization designed to strengthen launch communication and premium brand perception.',
    media: {
      image: 'https://images.unsplash.com/photo-1653299832314-5d3dc1e5a83c?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1MDZ8MHwxfHNlYXJjaHwyfHxhYnN0cmFjdCUyMDNEfGVufDB8fHx8MTc2OTM1MzE0N3ww&ixlib=rb-4.1.0&q=85&w=1200',
      alt: 'Abstract 3D geometric forms representing CGI and digital visualization',
    },
    servicesProvided: ['3D Product Modeling', 'Photorealistic Rendering', 'Animation', 'Key Visual Creation', 'Multi-Format Output'],
    deliverables: ['CGI Renders', 'Animation', 'Key Visuals', 'Digital Assets'],
    projectFocus: ['Product feature visualization', 'Premium brand perception', 'Multi-channel deployment', 'Campaign consistency'],
    caseStudy: {
      context: 'A premium consumer electronics brand needed product visualization assets for Japan that could communicate precision, quality, and product value without relying solely on traditional photography.',
      challenge: 'The visuals had to look highly refined across advertising and digital placements while maintaining technical realism, premium finish, and consistency across multiple output formats.',
      response: 'We built the work around photoreal CGI, controlled product framing, and asset systems designed to support campaign use across key launch touchpoints.',
      execution: 'Streetshow handled 3D modeling, rendering, animation, and key visual production, ensuring the assets were usable across campaign, digital, and presentation environments.',
      outcome: 'The result was a cleaner premium product presentation system designed to support launch communication, product storytelling, and more consistent brand perception in market.',
    },
    relatedServices: ['3d-cgi-production', '3d-anamorphic-billboards-japan'],
  },
  {
    slug: 'japan-luxury-resort-video-campaign',
    title: 'Hotel Video Campaign in Japan',
    proofLine: 'Hospitality · Brand Repositioning · 2024',
    client: 'International luxury hospitality operator',
    year: '2024',
    category: 'Hospitality',
    intro: 'A comprehensive creative strategy and content production project for a luxury resort group repositioning in the Japan market.',
    description: 'Creative strategy and hospitality content production designed to improve visibility, booking intent, and long-term brand position.',
    media: {
      image: 'https://images.unsplash.com/photo-1628414233354-bec86a0e35ce?crop=entropy&cs=srgb&fm=jpg&ixid=M3wxMjA3fDB8MHwxfGhvdGVsfGVufDB8fHx8MTc2OTM1MzE1MHww&ixlib=rb-4.1.0&q=85&w=1200',
      alt: 'Premium hospitality interior representing luxury hotel creative services',
    },
    servicesProvided: ['Creative Strategy', 'Video Production', 'Photography', 'Campaign Planning', 'Digital Optimization'],
    deliverables: ['Creative Strategy', 'Brand Video', 'Photography', 'Campaign Assets', 'Digital Content'],
    projectFocus: ['Brand repositioning', 'Booking conversion increase', 'Visibility improvement', 'Long-term revenue growth'],
    caseStudy: {
      context: 'An international luxury hospitality operator needed stronger creative assets to reposition a resort offer in Japan and improve the quality of demand coming through digital channels.',
      challenge: 'The brand needed to move beyond generic hotel marketing and communicate a more distinctive premium identity that could support visibility, booking intent, and long-term revenue.',
      response: 'We approached the project as a repositioning exercise, aligning creative strategy, visual direction, photography, and video around the guest experience and commercial objectives.',
      execution: 'Streetshow delivered creative strategy, campaign planning, video production, photography, and digital-ready assets built to support hospitality performance across channels.',
      outcome: 'The finished work gave the resort a stronger premium presentation framework, supporting better visibility, more qualified demand, and a clearer long-term brand position in market.',
    },
    relatedServices: ['hospitality-creative-strategy-japan', 'video-production-japan', 'photography-cgi-japan'],
  },
];

export function getCatalogService(slug: string) {
  return serviceCatalog.find((item) => item.slug === slug);
}

export function getCatalogProject(slug: string) {
  return projectCatalog.find((item) => item.slug === slug);
}
