export const aboutPageBilingual = {
  title: { en: 'About Streetshow Productions', ja: 'Streetshow Productionsについて' },
  intro: {
    en: 'Streetshow Productions is the Japan-entry, localization, and creative execution partner for premium brands. For teams that cannot afford a weak launch.',
    ja: 'Streetshow Productionsは、プレミアムブランドのための日本市場進出・ローカライズ・クリエイティブ実行パートナーです。弱いローンチが許されないチームのために。',
  },
  mission: {
    en: 'We help international companies adapt, position, and execute for Japan with the cultural precision, production discipline, and brand sensitivity this market demands.',
    ja: '国際企業が、この市場が求める文化的精度、制作規律、ブランド感度をもって、日本向けに適応・ポジショニング・実行できるよう支援します。',
  },
  positioningLabel: { en: 'Positioning', ja: 'ポジショニング' },
  positioning: {
    en: 'A premium Japan market entry, localization, and execution partner for high-end brands.',
    ja: 'ハイエンドブランドのための、日本市場進出・ローカライズ・実行パートナー。',
  },
  operatingEdgeLabel: { en: 'Operating Edge', ja: '事業上の優位性' },
  primaryVerticalLabel: { en: 'Primary Vertical', ja: '主要バーティカル' },
  primaryVerticalValue: { en: 'Luxury hospitality', ja: 'ラグジュアリーホスピタリティ' },
  coreCapabilityLabel: { en: 'Core Capability', ja: '中核能力' },
  coreCapabilityValue: { en: 'Japan market entry, localization, and execution', ja: '日本市場進出・ローカライズ・実行支援' },
  bestFitLabel: { en: 'Best Fit For', ja: '最適な対象' },
  operatingEdge: {
    en: 'Based in Fukuoka and Tokyo. Bilingual EN/JP. Built for local execution and international stakeholder alignment at once. We work with premium brands that need more than translation: local credibility, refined execution, and market-aware judgment.',
    ja: '福岡・東京を拠点に、EN/JPバイリンガルで対応。国内での実行と海外ステークホルダーとの連携を、同時に成立させる体制です。翻訳以上のもの、つまりローカルでの信頼性、洗練された実行力、市場を見据えた判断力を必要とするプレミアムブランドと取り組みます。',
  },
  credibility: {
    en: 'We back premium brands where strategic clarity, cultural nuance, and execution quality decide whether a launch works.',
    ja: '戦略の明確さ、文化的なニュアンス、実行品質がローンチの成否を決める、そんなプレミアムブランドを支えます。',
  },
  proofStrip: [
    { label: { en: 'Locations', ja: '拠点' }, value: { en: 'Fukuoka & Tokyo, Japan', ja: '福岡・東京' } },
    { label: { en: 'Execution', ja: '実行体制' }, value: { en: 'Bilingual EN/JP coordination', ja: 'EN/JPバイリンガル連携' } },
    { label: { en: 'Model', ja: 'モデル' }, value: { en: 'Strategy through delivery', ja: '戦略から納品まで' } },
  ],
  bestFit: [
    { en: 'Brands entering or repositioning in Japan', ja: '日本に進出または再構築するブランド' },
    { en: 'Teams that need strategy and execution together', ja: '戦略と実行を一体で必要とするチーム' },
    { en: 'Premium operators where brand perception and local credibility matter', ja: 'ブランド認知とローカルでの信頼性が重要なプレミアム事業者' },
  ],
};

export const contactPageBilingual = {
  title: { en: 'Discuss Your Project', ja: 'プロジェクトについて相談する' },
  subtitle: {
    en: 'We work with a select set of brands and operators where strategic clarity, cultural nuance, and execution quality decide whether a launch works.',
    ja: '戦略の明確さ、文化的なニュアンス、実行品質がローンチの成否を決める案件で、厳選したブランドや事業者と取り組みます。',
  },
  qualification: {
    en: 'Best suited for Japan market entry, hospitality repositioning, premium campaign execution, and localization-led brand work.',
    ja: '日本市場進出、ホスピタリティ再構築、プレミアムキャンペーン実行、ローカライズ主導のブランド案件に最適です。',
  },
  reassurance: {
    en: 'We review each inquiry carefully and respond to serious requests promptly.',
    ja: '各お問い合わせを丁寧に確認し、真剣なご相談には速やかに対応します。',
  },
  processNote: {
    en: 'A first call is where we assess fit, market context, and the level of support you need.',
    ja: '初回の打ち合わせで、適合性、市場背景、必要な支援レベルを確認します。',
  },
  contactInfoLabel: { en: 'Contact Information', ja: '連絡先情報' },
  emailLabel: { en: 'Email', ja: 'メール' },
  locationLabel: { en: 'Location', ja: '所在地' },
  directLabel: { en: 'Prefer to speak directly?', ja: '直接話しませんか？' },
  fieldLabels: {
    name: { en: 'Full Name', ja: 'お名前' },
    email: { en: 'Work Email', ja: '業務用メール' },
    company: { en: 'Company', ja: '会社名' },
    website: { en: 'Website', ja: 'Webサイト' },
    projectType: { en: 'Project Type', ja: 'プロジェクト種別' },
    budget: { en: 'Budget Range', ja: '予算レンジ' },
    timeline: { en: 'Timeline', ja: 'スケジュール' },
    location: { en: 'Location', ja: '所在地' },
    scope: { en: 'Japan Scope', ja: '日本市場での範囲' },
    details: { en: 'What are you trying to achieve in Japan?', ja: '日本市場で実現したいことは何ですか？' },
    hearAbout: { en: 'How did you hear about us?', ja: '当社をどこで知りましたか？' },
  },
  selectPlaceholder: { en: 'Select one', ja: '選択してください' },
  hearAboutOptions: [
    { en: 'Google search', ja: 'Google検索' },
    { en: 'ChatGPT / AI assistant (Perplexity, Claude, Gemini)', ja: 'ChatGPT・AIアシスタント（Perplexity、Claude、Gemini）' },
    { en: 'LinkedIn', ja: 'LinkedIn' },
    { en: 'Referral / word of mouth', ja: '紹介・口コミ' },
    { en: 'Industry event or trade fair', ja: '業界イベント・展示会' },
    { en: 'Found a Streetshow article or guide', ja: 'Streetshowの記事・ガイドから' },
    { en: 'Instagram / social media', ja: 'Instagram・SNS' },
    { en: 'Other', ja: 'その他' },
  ],
  projectTypeOptions: [
    { en: 'Japan Creative Performance Audit', ja: '日本向けクリエイティブ・パフォーマンス監査' },
    { en: 'Japan Market Entry & Localization', ja: '日本市場参入・ローカライズ' },
    { en: 'Video Production', ja: '映像制作' },
    { en: 'Hospitality Creative Strategy', ja: 'ホスピタリティ・クリエイティブ戦略' },
    { en: '3D Anamorphic Billboard', ja: '3Dアナモルフィックビルボード' },
    { en: 'Photography & CGI', ja: 'フォトグラフィー・CGI' },
    { en: 'Live Commerce & E-commerce Growth', ja: 'ライブコマース・EC成長支援' },
    { en: 'Other / Not sure yet', ja: 'その他・未定' },
  ],
  budgetOptions: [
    { en: 'Under ¥500,000', ja: '¥500,000未満' },
    { en: '¥500,000 – ¥1,000,000', ja: '¥500,000〜¥1,000,000' },
    { en: '¥1,000,000 – ¥3,000,000', ja: '¥1,000,000〜¥3,000,000' },
    { en: '¥3,000,000 – ¥10,000,000', ja: '¥3,000,000〜¥10,000,000' },
    { en: '¥10,000,000+', ja: '¥10,000,000以上' },
    { en: 'Not sure yet', ja: '未定' },
  ],
};
